"""
Add title column to projects

Revision ID: e72af3b72569
Revises: 502d820c3853
Create Date: 2024-10-28 08:53:06.657358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e72af3b72569'
down_revision: Union[str, None] = '502d820c3853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column('project_url', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column('updated_at', sa.DateTime(), nullable=True))

        # Removing alteration of the 'id' column
        # batch_op.alter_column('id',
        #        existing_type=sa.BIGINT(),
        #        server_default=None,
        #        type_=sa.Integer(),
        #        existing_nullable=False,
        #        autoincrement=True)

        batch_op.alter_column('created_at',
                              existing_type=postgresql.TIMESTAMP(
                                  timezone=True),
                              type_=sa.DateTime(),
                              nullable=True,
                              existing_server_default=sa.text('now()'))
        batch_op.create_index(batch_op.f(
            'ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_title'), [
                              'title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_title'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.alter_column('created_at',
                              existing_type=sa.DateTime(),
                              type_=postgresql.TIMESTAMP(timezone=True),
                              nullable=False,
                              existing_server_default=sa.text('now()'))

        # Removing alteration of the 'id' column during downgrade
        # batch_op.alter_column('id',
        #        existing_type=sa.Integer(),
        #        server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
        #        type_=sa.BIGINT(),
        #        existing_nullable=False,
        #        autoincrement=True)

        batch_op.drop_column('updated_at')
        batch_op.drop_column('project_url')
        batch_op.drop_column('image_url')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
